/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StadiumsRouteImport } from './routes/stadiums'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPhoneRouteImport } from './routes/reset-phone'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalDataRouteImport } from './routes/personal-data'
import { Route as MyRouteImport } from './routes/my'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StadiumsStadiumIdRouteImport } from './routes/stadiums_.$stadiumId'
import { Route as GamesGameIdRouteImport } from './routes/games_.$gameId'
import { Route as FriendsFriendIdRouteImport } from './routes/friends_.$friendId'
import { Route as ChatsConversationIdRouteImport } from './routes/chats_.$conversationId'
import { Route as ApiPitchesRouteImport } from './routes/api/pitches'
import { Route as ApiGeocodeSuggestRouteImport } from './routes/api/geocode-suggest'
import { Route as ApiGeocodeRouteImport } from './routes/api/geocode'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLogRouteImport } from './routes/admin.log'
import { Route as AdminGoalsRouteImport } from './routes/admin.goals'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as ApiAdminGrantRoleRouteImport } from './routes/api/admin/grant-role'

const StadiumsRoute = StadiumsRouteImport.update({
  id: '/stadiums',
  path: '/stadiums',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPhoneRoute = ResetPhoneRouteImport.update({
  id: '/reset-phone',
  path: '/reset-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataRoute = PersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumsStadiumIdRoute = StadiumsStadiumIdRouteImport.update({
  id: '/stadiums_/$stadiumId',
  path: '/stadiums/$stadiumId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games_/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/friends_/$friendId',
  path: '/friends/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/chats_/$conversationId',
  path: '/chats/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPitchesRoute = ApiPitchesRouteImport.update({
  id: '/api/pitches',
  path: '/api/pitches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeSuggestRoute = ApiGeocodeSuggestRouteImport.update({
  id: '/api/geocode-suggest',
  path: '/api/geocode-suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoalsRoute = AdminGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminGrantRoleRoute = ApiAdminGrantRoleRouteImport.update({
  id: '/api/admin/grant-role',
  path: '/api/admin/grant-role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/my': typeof MyRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-phone': typeof ResetPhoneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stadiums': typeof StadiumsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/geocode-suggest': typeof ApiGeocodeSuggestRoute
  '/api/pitches': typeof ApiPitchesRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/stadiums/$stadiumId': typeof StadiumsStadiumIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/grant-role': typeof ApiAdminGrantRoleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/my': typeof MyRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-phone': typeof ResetPhoneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stadiums': typeof StadiumsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/geocode-suggest': typeof ApiGeocodeSuggestRoute
  '/api/pitches': typeof ApiPitchesRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/stadiums/$stadiumId': typeof StadiumsStadiumIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/grant-role': typeof ApiAdminGrantRoleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/my': typeof MyRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-phone': typeof ResetPhoneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stadiums': typeof StadiumsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/api/geocode-suggest': typeof ApiGeocodeSuggestRoute
  '/api/pitches': typeof ApiPitchesRoute
  '/chats_/$conversationId': typeof ChatsConversationIdRoute
  '/friends_/$friendId': typeof FriendsFriendIdRoute
  '/games_/$gameId': typeof GamesGameIdRoute
  '/stadiums_/$stadiumId': typeof StadiumsStadiumIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/grant-role': typeof ApiAdminGrantRoleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chats'
    | '/create'
    | '/friends'
    | '/games'
    | '/my'
    | '/personal-data'
    | '/privacy'
    | '/profile'
    | '/reset-phone'
    | '/sitemap.xml'
    | '/stadiums'
    | '/admin/games'
    | '/admin/goals'
    | '/admin/log'
    | '/admin/users'
    | '/api/geocode'
    | '/api/geocode-suggest'
    | '/api/pitches'
    | '/chats/$conversationId'
    | '/friends/$friendId'
    | '/games/$gameId'
    | '/stadiums/$stadiumId'
    | '/u/$username'
    | '/admin/'
    | '/api/admin/grant-role'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/friends'
    | '/games'
    | '/my'
    | '/personal-data'
    | '/privacy'
    | '/profile'
    | '/reset-phone'
    | '/sitemap.xml'
    | '/stadiums'
    | '/admin/games'
    | '/admin/goals'
    | '/admin/log'
    | '/admin/users'
    | '/api/geocode'
    | '/api/geocode-suggest'
    | '/api/pitches'
    | '/chats/$conversationId'
    | '/friends/$friendId'
    | '/games/$gameId'
    | '/stadiums/$stadiumId'
    | '/u/$username'
    | '/admin'
    | '/api/admin/grant-role'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chats'
    | '/create'
    | '/friends'
    | '/games'
    | '/my'
    | '/personal-data'
    | '/privacy'
    | '/profile'
    | '/reset-phone'
    | '/sitemap.xml'
    | '/stadiums'
    | '/admin/games'
    | '/admin/goals'
    | '/admin/log'
    | '/admin/users'
    | '/api/geocode'
    | '/api/geocode-suggest'
    | '/api/pitches'
    | '/chats_/$conversationId'
    | '/friends_/$friendId'
    | '/games_/$gameId'
    | '/stadiums_/$stadiumId'
    | '/u/$username'
    | '/admin/'
    | '/api/admin/grant-role'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  FriendsRoute: typeof FriendsRoute
  GamesRoute: typeof GamesRoute
  MyRoute: typeof MyRoute
  PersonalDataRoute: typeof PersonalDataRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPhoneRoute: typeof ResetPhoneRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StadiumsRoute: typeof StadiumsRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  ApiGeocodeSuggestRoute: typeof ApiGeocodeSuggestRoute
  ApiPitchesRoute: typeof ApiPitchesRoute
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  StadiumsStadiumIdRoute: typeof StadiumsStadiumIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAdminGrantRoleRoute: typeof ApiAdminGrantRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stadiums': {
      id: '/stadiums'
      path: '/stadiums'
      fullPath: '/stadiums'
      preLoaderRoute: typeof StadiumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-phone': {
      id: '/reset-phone'
      path: '/reset-phone'
      fullPath: '/reset-phone'
      preLoaderRoute: typeof ResetPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data': {
      id: '/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof PersonalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadiums_/$stadiumId': {
      id: '/stadiums_/$stadiumId'
      path: '/stadiums/$stadiumId'
      fullPath: '/stadiums/$stadiumId'
      preLoaderRoute: typeof StadiumsStadiumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/$gameId': {
      id: '/games_/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends_/$friendId': {
      id: '/friends_/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats_/$conversationId': {
      id: '/chats_/$conversationId'
      path: '/chats/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pitches': {
      id: '/api/pitches'
      path: '/api/pitches'
      fullPath: '/api/pitches'
      preLoaderRoute: typeof ApiPitchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode-suggest': {
      id: '/api/geocode-suggest'
      path: '/api/geocode-suggest'
      fullPath: '/api/geocode-suggest'
      preLoaderRoute: typeof ApiGeocodeSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/goals': {
      id: '/admin/goals'
      path: '/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AdminGoalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/grant-role': {
      id: '/api/admin/grant-role'
      path: '/api/admin/grant-role'
      fullPath: '/api/admin/grant-role'
      preLoaderRoute: typeof ApiAdminGrantRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGamesRoute: typeof AdminGamesRoute
  AdminGoalsRoute: typeof AdminGoalsRoute
  AdminLogRoute: typeof AdminLogRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGamesRoute: AdminGamesRoute,
  AdminGoalsRoute: AdminGoalsRoute,
  AdminLogRoute: AdminLogRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  FriendsRoute: FriendsRoute,
  GamesRoute: GamesRoute,
  MyRoute: MyRoute,
  PersonalDataRoute: PersonalDataRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPhoneRoute: ResetPhoneRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StadiumsRoute: StadiumsRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  ApiGeocodeSuggestRoute: ApiGeocodeSuggestRoute,
  ApiPitchesRoute: ApiPitchesRoute,
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  FriendsFriendIdRoute: FriendsFriendIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  StadiumsStadiumIdRoute: StadiumsStadiumIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAdminGrantRoleRoute: ApiAdminGrantRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
