/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StadiumsRouteImport } from './routes/stadiums'
import { Route as ResetPhoneRouteImport } from './routes/reset-phone'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalDataRouteImport } from './routes/personal-data'
import { Route as MyRouteImport } from './routes/my'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as StadiumsStadiumIdRouteImport } from './routes/stadiums_.$stadiumId'
import { Route as PaySuccessRouteImport } from './routes/pay.success'
import { Route as PayFailRouteImport } from './routes/pay.fail'
import { Route as ManagerScheduleRouteImport } from './routes/manager.schedule'
import { Route as ManagerPricesRouteImport } from './routes/manager.prices'
import { Route as ManagerFinanceRouteImport } from './routes/manager.finance'
import { Route as ManagerChatsRouteImport } from './routes/manager.chats'
import { Route as ManagerCalendarRouteImport } from './routes/manager.calendar'
import { Route as GamesGameIdRouteImport } from './routes/games_.$gameId'
import { Route as FriendsFriendIdRouteImport } from './routes/friends_.$friendId'
import { Route as ChatsConversationIdRouteImport } from './routes/chats_.$conversationId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminLogRouteImport } from './routes/admin.log'
import { Route as AdminGoalsRouteImport } from './routes/admin.goals'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { ServerRoute as SitemapDotxmlServerRouteImport } from './routes/sitemap[.]xml'
import { ServerRoute as ApiUploadServerRouteImport } from './routes/api/upload'
import { ServerRoute as ApiPitchesServerRouteImport } from './routes/api/pitches'
import { ServerRoute as ApiMediaSignServerRouteImport } from './routes/api/media-sign'
import { ServerRoute as ApiMediaServerRouteImport } from './routes/api/media'
import { ServerRoute as ApiGeocodeSuggestServerRouteImport } from './routes/api/geocode-suggest'
import { ServerRoute as ApiGeocodeServerRouteImport } from './routes/api/geocode'
import { ServerRoute as ApiTelegramAuthServerRouteImport } from './routes/api/telegram/auth'
import { ServerRoute as ApiPaykeeperCreateServerRouteImport } from './routes/api/paykeeper/create'
import { ServerRoute as ApiPaykeeperCallbackServerRouteImport } from './routes/api/paykeeper/callback'
import { ServerRoute as ApiInternalSendPushServerRouteImport } from './routes/api/internal.send-push'
import { ServerRoute as ApiAdminGrantRoleServerRouteImport } from './routes/api/admin/grant-role'

const rootServerRouteImport = createServerRootRoute()

const StadiumsRoute = StadiumsRouteImport.update({
  id: '/stadiums',
  path: '/stadiums',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPhoneRoute = ResetPhoneRouteImport.update({
  id: '/reset-phone',
  path: '/reset-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataRoute = PersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumsStadiumIdRoute = StadiumsStadiumIdRouteImport.update({
  id: '/stadiums_/$stadiumId',
  path: '/stadiums/$stadiumId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/pay/success',
  path: '/pay/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PayFailRoute = PayFailRouteImport.update({
  id: '/pay/fail',
  path: '/pay/fail',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerScheduleRoute = ManagerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerPricesRoute = ManagerPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerFinanceRoute = ManagerFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerChatsRoute = ManagerChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerCalendarRoute = ManagerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ManagerRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games_/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/friends_/$friendId',
  path: '/friends/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsConversationIdRoute = ChatsConversationIdRouteImport.update({
  id: '/chats_/$conversationId',
  path: '/chats/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogRoute = AdminLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGoalsRoute = AdminGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const SitemapDotxmlServerRoute = SitemapDotxmlServerRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUploadServerRoute = ApiUploadServerRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPitchesServerRoute = ApiPitchesServerRouteImport.update({
  id: '/api/pitches',
  path: '/api/pitches',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMediaSignServerRoute = ApiMediaSignServerRouteImport.update({
  id: '/api/media-sign',
  path: '/api/media-sign',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiMediaServerRoute = ApiMediaServerRouteImport.update({
  id: '/api/media',
  path: '/api/media',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiGeocodeSuggestServerRoute = ApiGeocodeSuggestServerRouteImport.update({
  id: '/api/geocode-suggest',
  path: '/api/geocode-suggest',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiGeocodeServerRoute = ApiGeocodeServerRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiTelegramAuthServerRoute = ApiTelegramAuthServerRouteImport.update({
  id: '/api/telegram/auth',
  path: '/api/telegram/auth',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiPaykeeperCreateServerRoute =
  ApiPaykeeperCreateServerRouteImport.update({
    id: '/api/paykeeper/create',
    path: '/api/paykeeper/create',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiPaykeeperCallbackServerRoute =
  ApiPaykeeperCallbackServerRouteImport.update({
    id: '/api/paykeeper/callback',
    path: '/api/paykeeper/callback',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiInternalSendPushServerRoute =
  ApiInternalSendPushServerRouteImport.update({
    id: '/api/internal/send-push',
    path: '/api/internal/send-push',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiAdminGrantRoleServerRoute = ApiAdminGrantRoleServerRouteImport.update({
  id: '/api/admin/grant-role',
  path: '/api/admin/grant-role',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/manager': typeof ManagerRouteWithChildren
  '/my': typeof MyRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-phone': typeof ResetPhoneRoute
  '/stadiums': typeof StadiumsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/users': typeof AdminUsersRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/manager/calendar': typeof ManagerCalendarRoute
  '/manager/chats': typeof ManagerChatsRoute
  '/manager/finance': typeof ManagerFinanceRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/schedule': typeof ManagerScheduleRoute
  '/pay/fail': typeof PayFailRoute
  '/pay/success': typeof PaySuccessRoute
  '/stadiums/$stadiumId': typeof StadiumsStadiumIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/my': typeof MyRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-phone': typeof ResetPhoneRoute
  '/stadiums': typeof StadiumsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/users': typeof AdminUsersRoute
  '/chats/$conversationId': typeof ChatsConversationIdRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/manager/calendar': typeof ManagerCalendarRoute
  '/manager/chats': typeof ManagerChatsRoute
  '/manager/finance': typeof ManagerFinanceRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/schedule': typeof ManagerScheduleRoute
  '/pay/fail': typeof PayFailRoute
  '/pay/success': typeof PaySuccessRoute
  '/stadiums/$stadiumId': typeof StadiumsStadiumIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRoute
  '/create': typeof CreateRoute
  '/friends': typeof FriendsRoute
  '/games': typeof GamesRoute
  '/manager': typeof ManagerRouteWithChildren
  '/my': typeof MyRoute
  '/personal-data': typeof PersonalDataRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-phone': typeof ResetPhoneRoute
  '/stadiums': typeof StadiumsRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/goals': typeof AdminGoalsRoute
  '/admin/log': typeof AdminLogRoute
  '/admin/users': typeof AdminUsersRoute
  '/chats_/$conversationId': typeof ChatsConversationIdRoute
  '/friends_/$friendId': typeof FriendsFriendIdRoute
  '/games_/$gameId': typeof GamesGameIdRoute
  '/manager/calendar': typeof ManagerCalendarRoute
  '/manager/chats': typeof ManagerChatsRoute
  '/manager/finance': typeof ManagerFinanceRoute
  '/manager/prices': typeof ManagerPricesRoute
  '/manager/schedule': typeof ManagerScheduleRoute
  '/pay/fail': typeof PayFailRoute
  '/pay/success': typeof PaySuccessRoute
  '/stadiums_/$stadiumId': typeof StadiumsStadiumIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chats'
    | '/create'
    | '/friends'
    | '/games'
    | '/manager'
    | '/my'
    | '/personal-data'
    | '/privacy'
    | '/profile'
    | '/reset-phone'
    | '/stadiums'
    | '/admin/games'
    | '/admin/goals'
    | '/admin/log'
    | '/admin/users'
    | '/chats/$conversationId'
    | '/friends/$friendId'
    | '/games/$gameId'
    | '/manager/calendar'
    | '/manager/chats'
    | '/manager/finance'
    | '/manager/prices'
    | '/manager/schedule'
    | '/pay/fail'
    | '/pay/success'
    | '/stadiums/$stadiumId'
    | '/u/$username'
    | '/admin/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/create'
    | '/friends'
    | '/games'
    | '/my'
    | '/personal-data'
    | '/privacy'
    | '/profile'
    | '/reset-phone'
    | '/stadiums'
    | '/admin/games'
    | '/admin/goals'
    | '/admin/log'
    | '/admin/users'
    | '/chats/$conversationId'
    | '/friends/$friendId'
    | '/games/$gameId'
    | '/manager/calendar'
    | '/manager/chats'
    | '/manager/finance'
    | '/manager/prices'
    | '/manager/schedule'
    | '/pay/fail'
    | '/pay/success'
    | '/stadiums/$stadiumId'
    | '/u/$username'
    | '/admin'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chats'
    | '/create'
    | '/friends'
    | '/games'
    | '/manager'
    | '/my'
    | '/personal-data'
    | '/privacy'
    | '/profile'
    | '/reset-phone'
    | '/stadiums'
    | '/admin/games'
    | '/admin/goals'
    | '/admin/log'
    | '/admin/users'
    | '/chats_/$conversationId'
    | '/friends_/$friendId'
    | '/games_/$gameId'
    | '/manager/calendar'
    | '/manager/chats'
    | '/manager/finance'
    | '/manager/prices'
    | '/manager/schedule'
    | '/pay/fail'
    | '/pay/success'
    | '/stadiums_/$stadiumId'
    | '/u/$username'
    | '/admin/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRoute
  CreateRoute: typeof CreateRoute
  FriendsRoute: typeof FriendsRoute
  GamesRoute: typeof GamesRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  MyRoute: typeof MyRoute
  PersonalDataRoute: typeof PersonalDataRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPhoneRoute: typeof ResetPhoneRoute
  StadiumsRoute: typeof StadiumsRoute
  ChatsConversationIdRoute: typeof ChatsConversationIdRoute
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PayFailRoute: typeof PayFailRoute
  PaySuccessRoute: typeof PaySuccessRoute
  StadiumsStadiumIdRoute: typeof StadiumsStadiumIdRoute
  UUsernameRoute: typeof UUsernameRoute
}
export interface FileServerRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/geocode': typeof ApiGeocodeServerRoute
  '/api/geocode-suggest': typeof ApiGeocodeSuggestServerRoute
  '/api/media': typeof ApiMediaServerRoute
  '/api/media-sign': typeof ApiMediaSignServerRoute
  '/api/pitches': typeof ApiPitchesServerRoute
  '/api/upload': typeof ApiUploadServerRoute
  '/api/admin/grant-role': typeof ApiAdminGrantRoleServerRoute
  '/api/internal/send-push': typeof ApiInternalSendPushServerRoute
  '/api/paykeeper/callback': typeof ApiPaykeeperCallbackServerRoute
  '/api/paykeeper/create': typeof ApiPaykeeperCreateServerRoute
  '/api/telegram/auth': typeof ApiTelegramAuthServerRoute
}
export interface FileServerRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/geocode': typeof ApiGeocodeServerRoute
  '/api/geocode-suggest': typeof ApiGeocodeSuggestServerRoute
  '/api/media': typeof ApiMediaServerRoute
  '/api/media-sign': typeof ApiMediaSignServerRoute
  '/api/pitches': typeof ApiPitchesServerRoute
  '/api/upload': typeof ApiUploadServerRoute
  '/api/admin/grant-role': typeof ApiAdminGrantRoleServerRoute
  '/api/internal/send-push': typeof ApiInternalSendPushServerRoute
  '/api/paykeeper/callback': typeof ApiPaykeeperCallbackServerRoute
  '/api/paykeeper/create': typeof ApiPaykeeperCreateServerRoute
  '/api/telegram/auth': typeof ApiTelegramAuthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/api/geocode': typeof ApiGeocodeServerRoute
  '/api/geocode-suggest': typeof ApiGeocodeSuggestServerRoute
  '/api/media': typeof ApiMediaServerRoute
  '/api/media-sign': typeof ApiMediaSignServerRoute
  '/api/pitches': typeof ApiPitchesServerRoute
  '/api/upload': typeof ApiUploadServerRoute
  '/api/admin/grant-role': typeof ApiAdminGrantRoleServerRoute
  '/api/internal/send-push': typeof ApiInternalSendPushServerRoute
  '/api/paykeeper/callback': typeof ApiPaykeeperCallbackServerRoute
  '/api/paykeeper/create': typeof ApiPaykeeperCreateServerRoute
  '/api/telegram/auth': typeof ApiTelegramAuthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/sitemap.xml'
    | '/api/geocode'
    | '/api/geocode-suggest'
    | '/api/media'
    | '/api/media-sign'
    | '/api/pitches'
    | '/api/upload'
    | '/api/admin/grant-role'
    | '/api/internal/send-push'
    | '/api/paykeeper/callback'
    | '/api/paykeeper/create'
    | '/api/telegram/auth'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/sitemap.xml'
    | '/api/geocode'
    | '/api/geocode-suggest'
    | '/api/media'
    | '/api/media-sign'
    | '/api/pitches'
    | '/api/upload'
    | '/api/admin/grant-role'
    | '/api/internal/send-push'
    | '/api/paykeeper/callback'
    | '/api/paykeeper/create'
    | '/api/telegram/auth'
  id:
    | '__root__'
    | '/sitemap.xml'
    | '/api/geocode'
    | '/api/geocode-suggest'
    | '/api/media'
    | '/api/media-sign'
    | '/api/pitches'
    | '/api/upload'
    | '/api/admin/grant-role'
    | '/api/internal/send-push'
    | '/api/paykeeper/callback'
    | '/api/paykeeper/create'
    | '/api/telegram/auth'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  SitemapDotxmlServerRoute: typeof SitemapDotxmlServerRoute
  ApiGeocodeServerRoute: typeof ApiGeocodeServerRoute
  ApiGeocodeSuggestServerRoute: typeof ApiGeocodeSuggestServerRoute
  ApiMediaServerRoute: typeof ApiMediaServerRoute
  ApiMediaSignServerRoute: typeof ApiMediaSignServerRoute
  ApiPitchesServerRoute: typeof ApiPitchesServerRoute
  ApiUploadServerRoute: typeof ApiUploadServerRoute
  ApiAdminGrantRoleServerRoute: typeof ApiAdminGrantRoleServerRoute
  ApiInternalSendPushServerRoute: typeof ApiInternalSendPushServerRoute
  ApiPaykeeperCallbackServerRoute: typeof ApiPaykeeperCallbackServerRoute
  ApiPaykeeperCreateServerRoute: typeof ApiPaykeeperCreateServerRoute
  ApiTelegramAuthServerRoute: typeof ApiTelegramAuthServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stadiums': {
      id: '/stadiums'
      path: '/stadiums'
      fullPath: '/stadiums'
      preLoaderRoute: typeof StadiumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-phone': {
      id: '/reset-phone'
      path: '/reset-phone'
      fullPath: '/reset-phone'
      preLoaderRoute: typeof ResetPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data': {
      id: '/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof PersonalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadiums_/$stadiumId': {
      id: '/stadiums_/$stadiumId'
      path: '/stadiums/$stadiumId'
      fullPath: '/stadiums/$stadiumId'
      preLoaderRoute: typeof StadiumsStadiumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/pay/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/fail': {
      id: '/pay/fail'
      path: '/pay/fail'
      fullPath: '/pay/fail'
      preLoaderRoute: typeof PayFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/schedule': {
      id: '/manager/schedule'
      path: '/schedule'
      fullPath: '/manager/schedule'
      preLoaderRoute: typeof ManagerScheduleRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/prices': {
      id: '/manager/prices'
      path: '/prices'
      fullPath: '/manager/prices'
      preLoaderRoute: typeof ManagerPricesRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/finance': {
      id: '/manager/finance'
      path: '/finance'
      fullPath: '/manager/finance'
      preLoaderRoute: typeof ManagerFinanceRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/chats': {
      id: '/manager/chats'
      path: '/chats'
      fullPath: '/manager/chats'
      preLoaderRoute: typeof ManagerChatsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/calendar': {
      id: '/manager/calendar'
      path: '/calendar'
      fullPath: '/manager/calendar'
      preLoaderRoute: typeof ManagerCalendarRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/games_/$gameId': {
      id: '/games_/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends_/$friendId': {
      id: '/friends_/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats_/$conversationId': {
      id: '/chats_/$conversationId'
      path: '/chats/$conversationId'
      fullPath: '/chats/$conversationId'
      preLoaderRoute: typeof ChatsConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/log': {
      id: '/admin/log'
      path: '/log'
      fullPath: '/admin/log'
      preLoaderRoute: typeof AdminLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/goals': {
      id: '/admin/goals'
      path: '/goals'
      fullPath: '/admin/goals'
      preLoaderRoute: typeof AdminGoalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/pitches': {
      id: '/api/pitches'
      path: '/api/pitches'
      fullPath: '/api/pitches'
      preLoaderRoute: typeof ApiPitchesServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/media-sign': {
      id: '/api/media-sign'
      path: '/api/media-sign'
      fullPath: '/api/media-sign'
      preLoaderRoute: typeof ApiMediaSignServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/media': {
      id: '/api/media'
      path: '/api/media'
      fullPath: '/api/media'
      preLoaderRoute: typeof ApiMediaServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/geocode-suggest': {
      id: '/api/geocode-suggest'
      path: '/api/geocode-suggest'
      fullPath: '/api/geocode-suggest'
      preLoaderRoute: typeof ApiGeocodeSuggestServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/telegram/auth': {
      id: '/api/telegram/auth'
      path: '/api/telegram/auth'
      fullPath: '/api/telegram/auth'
      preLoaderRoute: typeof ApiTelegramAuthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/paykeeper/create': {
      id: '/api/paykeeper/create'
      path: '/api/paykeeper/create'
      fullPath: '/api/paykeeper/create'
      preLoaderRoute: typeof ApiPaykeeperCreateServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/paykeeper/callback': {
      id: '/api/paykeeper/callback'
      path: '/api/paykeeper/callback'
      fullPath: '/api/paykeeper/callback'
      preLoaderRoute: typeof ApiPaykeeperCallbackServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/internal/send-push': {
      id: '/api/internal/send-push'
      path: '/api/internal/send-push'
      fullPath: '/api/internal/send-push'
      preLoaderRoute: typeof ApiInternalSendPushServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/admin/grant-role': {
      id: '/api/admin/grant-role'
      path: '/api/admin/grant-role'
      fullPath: '/api/admin/grant-role'
      preLoaderRoute: typeof ApiAdminGrantRoleServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGamesRoute: typeof AdminGamesRoute
  AdminGoalsRoute: typeof AdminGoalsRoute
  AdminLogRoute: typeof AdminLogRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGamesRoute: AdminGamesRoute,
  AdminGoalsRoute: AdminGoalsRoute,
  AdminLogRoute: AdminLogRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManagerRouteChildren {
  ManagerCalendarRoute: typeof ManagerCalendarRoute
  ManagerChatsRoute: typeof ManagerChatsRoute
  ManagerFinanceRoute: typeof ManagerFinanceRoute
  ManagerPricesRoute: typeof ManagerPricesRoute
  ManagerScheduleRoute: typeof ManagerScheduleRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerCalendarRoute: ManagerCalendarRoute,
  ManagerChatsRoute: ManagerChatsRoute,
  ManagerFinanceRoute: ManagerFinanceRoute,
  ManagerPricesRoute: ManagerPricesRoute,
  ManagerScheduleRoute: ManagerScheduleRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRoute,
  CreateRoute: CreateRoute,
  FriendsRoute: FriendsRoute,
  GamesRoute: GamesRoute,
  ManagerRoute: ManagerRouteWithChildren,
  MyRoute: MyRoute,
  PersonalDataRoute: PersonalDataRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPhoneRoute: ResetPhoneRoute,
  StadiumsRoute: StadiumsRoute,
  ChatsConversationIdRoute: ChatsConversationIdRoute,
  FriendsFriendIdRoute: FriendsFriendIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PayFailRoute: PayFailRoute,
  PaySuccessRoute: PaySuccessRoute,
  StadiumsStadiumIdRoute: StadiumsStadiumIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  SitemapDotxmlServerRoute: SitemapDotxmlServerRoute,
  ApiGeocodeServerRoute: ApiGeocodeServerRoute,
  ApiGeocodeSuggestServerRoute: ApiGeocodeSuggestServerRoute,
  ApiMediaServerRoute: ApiMediaServerRoute,
  ApiMediaSignServerRoute: ApiMediaSignServerRoute,
  ApiPitchesServerRoute: ApiPitchesServerRoute,
  ApiUploadServerRoute: ApiUploadServerRoute,
  ApiAdminGrantRoleServerRoute: ApiAdminGrantRoleServerRoute,
  ApiInternalSendPushServerRoute: ApiInternalSendPushServerRoute,
  ApiPaykeeperCallbackServerRoute: ApiPaykeeperCallbackServerRoute,
  ApiPaykeeperCreateServerRoute: ApiPaykeeperCreateServerRoute,
  ApiTelegramAuthServerRoute: ApiTelegramAuthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
